from pathlib import Path
from tempfile import TemporaryDirectory

import torch
from torch import nn

from color_pass_through.cli.train_projector import build_parser
from color_pass_through.models.projector import CameraDisplayProjector, ProjectorSettings
from color_pass_through.training.visualization import ProjectorLUTExporter


class IdentityProjector(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.anchor = nn.Parameter(torch.zeros(()))

    def map_rgb_samples(self, rgb: torch.Tensor) -> torch.Tensor:
        return rgb + 0.0 * self.anchor


def test_raw_green_context_lut_features_match_legacy_rgbg_order() -> None:
    model = CameraDisplayProjector(
        ProjectorSettings(
            input_mode="raw_green_context",
            encoding="identity",
            hidden_dim=4,
            hidden_layers=0,
        )
    )
    rgb = torch.tensor([[0.1, 0.2, 0.3]])
    expected = model.mlp(model.encoder(torch.tensor([[0.1, 0.2, 0.3, 0.2]])))
    assert torch.equal(model.map_rgb_samples(rgb), expected)


def test_projector_lut_export_writes_legacy_cube_and_quiver() -> None:
    with TemporaryDirectory() as directory:
        output = Path(directory)
        exporter = ProjectorLUTExporter(
            output, size=3, every_n_epochs=10, chunk_pixels=5, vis_subsample=1
        )
        assert not exporter.maybe_export(IdentityProjector(), epoch=8)
        assert exporter.maybe_export(IdentityProjector(), epoch=9)
        cube = output / "epoch009_size3.cube"
        visualization = output / "epoch009_size3_vis.png"
        assert cube.is_file()
        assert visualization.is_file()
        lines = cube.read_text(encoding="utf-8").splitlines()
        assert lines[:4] == [
            "# Generated by NGPColorMap (periodic export)",
            "LUT_3D_SIZE 3",
            "DOMAIN_MIN 0.0 0.0 0.0",
            "DOMAIN_MAX 1.0 1.0 1.0",
        ]
        assert len(lines) == 4 + 3**3
        assert lines[4] == "0.000000 0.000000 0.000000"
        assert lines[-1] == "1.000000 1.000000 1.000000"


def test_projector_lut_defaults_match_legacy_run() -> None:
    args = build_parser().parse_args(["--config", "device.yaml", "--output", "run"])
    assert args.lut_visualization
    assert args.lut_size == 33
    assert args.lut_every_n_epochs == 10
    assert args.lut_chunk_pixels == 262_144
    assert args.lut_vis_subsample == 3
    assert args.lut_vis_vec_scale == 1.0
    assert args.lut_vis_arrow_length == 0.08
